// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEYvvE_WAIOx6QOkCFsRTAWZ29WYC2cwA',
    appId: '1:3925576112:web:266b9d0ced168fd4bcae75',
    messagingSenderId: '3925576112',
    projectId: 'wattwise-cd1b5',
    authDomain: 'wattwise-cd1b5.firebaseapp.com',
    storageBucket: 'wattwise-cd1b5.firebasestorage.app',
    measurementId: 'G-LT1S3X2SV8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB_8Z_NqgRytEQ-pBMK0cwqxR-txAw5pE',
    appId: '1:3925576112:android:a820fa82cead9f6ebcae75',
    messagingSenderId: '3925576112',
    projectId: 'wattwise-cd1b5',
    storageBucket: 'wattwise-cd1b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU2oAF-P5xDHWh_WlJlzrtc-f0BBLjYzU',
    appId: '1:3925576112:ios:d9955d9f1b65cf4dbcae75',
    messagingSenderId: '3925576112',
    projectId: 'wattwise-cd1b5',
    storageBucket: 'wattwise-cd1b5.firebasestorage.app',
    iosBundleId: 'com.example.wattwiseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU2oAF-P5xDHWh_WlJlzrtc-f0BBLjYzU',
    appId: '1:3925576112:ios:d9955d9f1b65cf4dbcae75',
    messagingSenderId: '3925576112',
    projectId: 'wattwise-cd1b5',
    storageBucket: 'wattwise-cd1b5.firebasestorage.app',
    iosBundleId: 'com.example.wattwiseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEYvvE_WAIOx6QOkCFsRTAWZ29WYC2cwA',
    appId: '1:3925576112:web:730fd78ea14c2208bcae75',
    messagingSenderId: '3925576112',
    projectId: 'wattwise-cd1b5',
    authDomain: 'wattwise-cd1b5.firebaseapp.com',
    storageBucket: 'wattwise-cd1b5.firebasestorage.app',
    measurementId: 'G-YBTH82TVQ3',
  );
}
